view_position = ["AP", "PA", "LATERAL", "LL", ""]
disease_location_organ = [
    "costophrenic sinus",
    "left base",
    "ventricle",
    "mediastinal contour",
    "left basal",
    "right lung apex",
    "hemidiaphragms",
    "bronchovascular",
    "lobe",
    "parenchymal",
    "hila",
    "stomach",
    "bony structures",
    "right upper lobe",
    "vein",
    "pulmonary vascularity",
    "vessels",
    "aortic",
    "aortic valve",
    "thoracic",
    "pectoral",
    "left hemidiaphragm",
    "bony",
    "hemidiaphragmatic contour",
    "right atrium",
    "both lower",
    "apical",
    "aortic knob",
    "displaced",
    "abnormalities",
    "mediastinal and hilar contours",
    "left chest wall",
    "right hemidiaphragm",
    "distal",
    "left apical",
    "tube",
    "basilar",
    "low",
    "right apex",
    "port-a-cath",
    "et tube",
    "silhouette",
    "nasogastric tube",
    "right middle lobe",
    "vasculature",
    "pleura",
    "thoracic spine",
    "upper zone",
    "surfaces",
    "picc line",
    "diaphragm",
    "silhouettes",
    "subcutaneous",
    "pulmonary vasculature",
    "pleural",
    "mediastinal",
    "osseous",
    "pulmonary artery",
    "right hilar",
    "alveolar",
    "lower thoracic",
    "lateral",
    "right lower lobe",
    "lingula",
    "aorta",
    "venous",
    "right apical",
    "right chest wall",
    "bilateral lower",
    "upper",
    "right infrahilar",
    "cardiopulmonary",
    "hiatal",
    "perihilar",
    "contour",
    "lower",
    "carinal",
    "focal",
    "mid thoracic",
    "vertebral body",
    "central",
    "both",
    "costophrenic angles",
    "region",
    "chest",
    "left mid and lower",
    "interstitial",
    "internal jugular",
    "lymphadenopathy",
    "left upper",
    "airspace",
    "multifocal",
    "lung base",
    "pulmonary venous",
    "hilar",
    "ribs",
    "left lower lobe",
    "base",
    "lung",
    "right basal",
    "cardiomediastinal silhouette",
    "right middle and lower",
    "right lower",
    "catheter",
    "bilateral",
    "trachea",
    "hemi thorax",
    "right lateral",
    "chest wall",
    "bone",
    "contours",
    "descending",
    "overt",
    "right lung",
    "bibasal",
    "veins",
    "mid and lower",
    "endotracheal tube",
    "retrocardiac",
    "humerus",
    "left retrocardiac",
    "sternal wires",
    "right mid lung",
    "tracheostomy tube",
    "left",
    "subclavian",
    "left lung base",
    "left subclavian",
    "abdomen",
    "descending aorta",
    "right upper quadrant",
    "left mid",
    "carina",
    "lower lobes",
    "intrathoracic",
    "apex",
    "lungs",
    "right-sided",
    "cavoatrial junction",
    "middle",
    "lower lobe",
    "spine",
    "bones",
    "right upper",
    "mediastinal and hilar",
    "na",
    "adenopathy",
    "hilus",
    "clavicle",
    "upper lobe",
    "thoracic aorta",
    "mid",
    "right",
    "cardiac silhouette",
    "right perihilar",
    "cardiac",
    "right ventricle",
    "line",
    "lingular",
    "left perihilar",
    "adjacent",
    "underlying",
    "right base",
    "hilum",
    "aortic arch",
    "pericardial",
    "right basilar",
    "left-sided",
    "pulmonary",
    "pulmonary arteries",
    "osseous structures",
    "lobes",
    "shoulder",
    "right mid and lower",
    "zone",
    "left lung",
    "mid svc",
    "subdiaphragmatic",
    "mediastinum",
    "posterior",
    "vascular",
    "left mid lung",
    "thoracolumbar junction",
    "rib",
    "lung bases",
    "cardiomediastinal",
    "pulmonary venous pressure",
    "basal",
    "heart",
    "ng tube",
    "areas",
    "biapical",
    "right lung bases",
    "hemithorax",
    "left lateral",
    "atrium",
    "hilar and mediastinal",
    "left lower",
    "upper abdomen",
    "left upper quadrant",
    "pulmonary vascular",
    "bases",
    "lymph nodes",
    "both bases",
    "pericardium",
    "costophrenic angle",
    "mediastinal contours",
    "right lung base",
    "infrahilar",
    "bibasilar",
    "left pectoral",
    "soft tissues",
    "right middle",
    "esophagus",
    "lung apices",
    "pulmonary vessels",
    "hemidiaphragm",
    "right mid",
    "right internal jugular",
    "cardiac and mediastinal",
    "left basilar",
    "lymph node",
    "cardiomediastinal and hilar",
    "lung parenchyma",
    "both lung bases",
]
disease_adjective = [
    "concurrent",
    "vague",
    "probably",
    "dilated",
    "biapical",
    "small if any",
    "less prominent",
    "widening",
    "bibasal",
    "resolving",
    "consistent with",
    "subsequent",
    "smaller",
    "decreasing",
    "minimally increased",
    "postoperative",
    "healed",
    "worse",
    "worrisome",
    "significant",
    "potentially",
    "old healed",
    "asymmetrical",
    "scarring",
    "similar",
    "complete",
    "little",
    "acute",
    "prior",
    "moderate-to-severe",
    "perihilar",
    "loculated",
    "progressive",
    "possibility of",
    "basilar",
    "slightly improved",
    "infectious",
    "ill-defined",
    "lungs",
    "central",
    "supervening",
    "subsegmental",
    "massive",
    "hyperinflation",
    "partial",
    "crowding",
    "some",
    "moderate to large",
    "minor",
    "tortuosity",
    "vascular",
    "degenerative",
    "subcutaneous",
    "consolidation",
    "heterogeneous",
    "right lower",
    "presumed",
    "slightly increased",
    "moderately severe",
    "mediastinal",
    "small-to-moderate",
    "standard",
    "atelectatic",
    "upper",
    "concerning",
    "diffuse bilateral",
    "hazy",
    "interstitial",
    "top-normal",
    "moderately",
    "infection",
    "pre-existing",
    "associated",
    "blunting",
    "layering",
    "streaky",
    "left-sided",
    "moderately enlarged",
    "early",
    "dense",
    "widespread",
    "right-sided",
    "intact",
    "old",
    "interval improvement",
    "tiny",
    "improvement",
    "tortuous",
    "decrease",
    "left lower",
    "elevated",
    "elevation",
    "unremarkable",
    "interval increase",
    "moderate to severe",
    "previous",
    "marked",
    "pleural",
    "asymmetric",
    "small to moderate",
    "hyperinflated",
    "increase",
    "prominence",
    "resolved",
    "focal",
    "developing",
    "prominent",
    "improving",
    "volume loss",
    "worsened",
    "mild-to-moderate",
    "interval",
    "residual",
    "adjacent",
    "aspiration",
    "compressive",
    "retrocardiac",
    "lower",
    "constant",
    "linear",
    "known",
    "underlying",
    "subtle",
    "slight",
    "multiple",
    "likely",
    "trace",
    "continued",
    "mild to moderate",
    "calcified",
    "mildly enlarged",
    "mildly",
    "probable",
    "multifocal",
    "superimposed",
    "enlargement",
    "extensive",
    "diffuse",
    "increasing",
    "clear",
    "patchy",
    "substantial",
    "chronic",
    "enlarged",
    "borderline",
    "worsening",
    "large",
    "possible",
    "decreased",
    "bibasilar",
    "severe",
    "improved",
    "persistent",
    "bilateral",
    "left",
    "right",
    "increased",
    "minimal",
    "stable",
    "low",
    "normal",
    "new",
    "unchanged",
    "moderate",
    "small",
    "mild",
]
disease_type = [
    "ascites",
    "pulmonary embolism",
    "pleural fluid",
    "pseudoaneurysm",
    "pulmonary nodules",
    "pneumoperitoneum",
    "dislocation",
    "inflammation",
    "hyperinflation",
    "tracheostomy tube",
    "pulmonary fibrosis",
    "infectious process",
    "cardiac enlargement",
    "bronchiectasis",
    "lesion",
    "cyst",
    "abscess",
    "embolism",
    "pneumomediastinum",
    "density",
    "granuloma",
    "adenopathy",
    "pacemaker",
    "subcutaneous emphysema",
    "hemorrhage",
    "dilatation",
    "nodules",
    "infiltrate",
    "aneurysm",
    "tension",
    "interstitial markings",
    "scoliosis",
    "fibrosis",
    "copd",
    "hernia",
    "hematoma",
    "hiatal hernia",
    "lymphadenopathy",
    "vascular engorgement",
    "occlusion",
    "thrombosis",
    "engorgement",
    "aeration",
    "nodule",
    "calcification",
    "scarring",
    "infection",
    "fracture",
    "emphysema",
    "pneumothoraces",
    "abnormalities",
    "vascular congestion",
    "opacification",
    "consolidation",
    "opacity",
    "cardiomegaly",
    "edema",
    "pneumonia",
    "atelectasis",
    "effusion",
    "pneumothorax",
]
description_book = {
    "ascites": "May show elevation of the diaphragm or a fluid wave on ultrasound due to accumulation of fluid in the abdominal cavity.",
    "pulmonary embolism": "Can cause areas of the lung to appear darker due to infarction or a wedge-shaped (Hampton hump) opacity; may also cause enlargement of pulmonary arteries.",
    "pleural fluid": "Appears as a homogenous density, usually in the lower lung fields or as a meniscus sign along the chest wall, indicating fluid accumulation in the pleural space.",
    "pseudoaneurysm": "An outpouching of an arterial wall that can appear as a rounded or saccular density adjacent to blood vessels, often requiring other imaging modalities to confirm.",
    "pulmonary nodules": "Small, rounded opacities within the lung parenchyma, which can vary in size and number.",
    "pneumoperitoneum": "Free air in the abdominal cavity that can accumulate under the diaphragm, appearing as a sharp line of lucency on an upright X-ray.",
    "dislocation": "Misalignment of bone joints, usually visible in the shoulder or neck area, where bones are not in their normal positions.",
    "inflammation": "May manifest as increased opacity due to fluid accumulation or swelling in the lung tissue or surrounding structures.",
    "hyperinflation": "Over-expanded lung fields, flattened diaphragms, and increased retrosternal air space, commonly seen in obstructive lung diseases.",
    "tracheostomy tube": "A radiopaque line or shadow within the trachea indicating the presence of a tracheostomy tube used for ventilation.",
    "pulmonary fibrosis": "Reticular markings, honeycombing, and possibly traction bronchiectasis, indicating stiff, scarred lung tissue.",
    "infectious process": "Variable appearance, from focal to diffuse opacities, consolidation, or cavitation, depending on the type and extent of the infection.",
    "cardiac enlargement": "Enlarged cardiac silhouette exceeding the normal size limits for the heart on the chest X-ray.",
    "bronchiectasis": "Abnormally dilated and thick-walled bronchi that can appear as ring-like or tubular structures on the X-ray.",
    "lesion": "A general term for an abnormal area; on an X-ray, it appears as an area of increased density or opacity.",
    "cyst": "A fluid-filled space that can appear as a round, well-defined lucency or opacity, depending on its content and wall thickness.",
    "abscess": "Appears as a round or ovoid density, often with a fluid level indicating the presence of pus in a new or pre-existing cavity.",
    "embolism": "A blockage in a blood vessel that may not be directly visible on X-ray but could lead to areas of increased or decreased opacity in the lung.",
    "pneumomediastinum": "Free air in the mediastinal space, appearing as linear or streaky lucencies outlining the mediastinal structures.",
    "density": "A region that appears more white on the X-ray film, indicating something denser than air, such as fluid, bone, or mass.",
    "granuloma": "A small, localized, rounded density often resulting from past inflammation or infection.",
    "adenopathy": "Enlarged lymph nodes that appear as rounded opacities, typically in the mediastinal or hilar regions.",
    "pacemaker": "Visible as wires and a generator case that are radiopaque, usually seen in the left upper chest area.",
    "subcutaneous emphysema": "Air in the subcutaneous tissues that appears as streaky or bubbly lucencies under the skin, often around the neck or chest wall.",
    "hemorrhage": "Depending on its location, may cause increased opacity due to blood in the lung tissue or an air-fluid level if in a body cavity.",
    "dilatation": "Enlargement of airways or blood vessels, appearing wider than normal on the X-ray.",
    "nodules": "Similar to pulmonary nodules, these are small, rounded densities within the lung fields.",
    "infiltrate": "A diffuse area of increased opacity in the lung, suggesting inflammation, infection, or other processes affecting the lung parenchyma.",
    "aneurysm": "Localized dilatation of a blood vessel that may appear as an abnormal rounded or oval shadow, but is more clearly seen on CT or MRI.",
    "tension": "This term is not typically descriptive of an X-ray finding, but in the context of tension pneumothorax, it would show a collapsed lung and shift of mediastinal structures away from the affected side due to high intrapleural pressure.",
    "interstitial markings": "Normally invisible lines and dots representing the lung support structure become more prominent, looking like a network or mesh of lines crisscrossing the lung fields.",
    "scoliosis": "A sideways curvature of the spine that can make the ribs appear uneven on an X-ray and may cause the lung fields to look asymmetrical.",
    "fibrosis": "Scarred and stiff lung tissue that appears denser (whiter) than healthy tissue, often with a reticular pattern or honeycombing in advanced cases.",
    "copd": "Over-expanded lungs with flattened diaphragms and large, dark (lucent) areas that indicate air trapping.",
    "hernia": "An abnormal protrusion of an organ or tissue that may show up as an unexpected mass or bulge in the areas adjacent to the diaphragm.",
    "hematoma": "A collection of blood outside blood vessels that appears as a localized, denser (whiter) area on X-ray.",
    "hiatal hernia": "Part of the stomach protrudes upward through the diaphragm and may appear as an abnormal shadow above the diaphragm.",
    "lymphadenopathy": "Enlarged lymph nodes that may show up as rounded, denser (whiter) spots or clusters, usually near the center of the chest in the mediastinal or hilar regions.",
    "vascular engorgement": "Blood vessels, especially those leading to the heart, look more prominent and wider than usual, indicating increased blood flow or volume.",
    "occlusion": "A blockage in a blood vessel or hollow organ that can result in a lack of blood flow and a corresponding area of increased opacity if infarction occurs.",
    "thrombosis": "A blood clot within a vessel that may not be directly visible but could cause a region of the lung to appear abnormal due to decreased blood flow.",
    "engorgement": "Similar to vascular engorgement, where the vessels, particularly around the heart and lungs, appear fuller and more pronounced.",
    "aeration": "A term for how well the lungs are filled with air; poorly aerated lungs may look more solid (whiter), while well-aerated lungs are dark (lucent).",
    "nodule": "A small, rounded shadow that stands out from the surrounding lung tissue; can be solitary or multiple.",
    "calcification": "A white, dense spot or area within a nodule or other tissue indicating deposition of calcium.",
    "scarring": "Appears as irregular lines or bands of denser tissue, often as a result of past inflammation or injury.",
    "infection": "Can vary but often shows up as areas of consolidation or opacity where the lung tissue is filled with fluid or pus.",
    "fracture": "Breaks in bones that appear as dark lines across the white bone structure on X-ray.",
    "emphysema": "Areas of the lung that look unusually clear (dark on X-ray) due to the destruction of lung tissue and air sacs, with a decrease in vascular markings.",
    "pneumothoraces": "Presence of air in the pleural space that shows up as a clear space (dark area) between the lung and the chest wall.",
    "abnormalities": "General term for any unusual findings on an X-ray which can include unexpected shapes, sizes, or densities in the lung fields.",
    "vascular congestion": "The blood vessels in the lung appear more prominent and numerous, often associated with heart failure.",
    "opacification": "Areas that appear white or grayish and cannot be seen through, suggesting the presence of fluid, cells, or other material.",
    "consolidation": "A region of lung tissue that has filled with liquid instead of air, appearing as a uniform area of increased whiteness.",
    "opacity": "Any area that appears whiter or more solid than it should, indicating something is blocking the passage of X-rays.",
    "cardiomegaly": "An enlarged heart silhouette that takes up more space than normal on the X-ray film.",
    "edema": "Excess fluid in the lung tissue, which may present as a diffuse haziness across the lung fields.",
    "pneumonia": "An infection causing consolidation, often seen as patchy or confluent white areas within the lung fields.",
    "atelectasis": "Collapse of lung tissue, showing as streaky opacities or anarea of increased density (whiteness) on the X-ray, sometimes with a shift of the surrounding structures.",
    "effusion": "An accumulation of fluid between the lung and chest wall that appears as a homogenous, dense area, often with a meniscus at the lung base.",
    "pneumothorax": "Air in the pleural space causing part of the lung to collapse, visible as a sharp line with no lung markings beyond it and a clear space where the lung has collapsed.",
}
